apiVersion: v1
kind: Secret
metadata:
  name: edtech-secrets
type: Opaque
data:
  WEBHOOK_SECRET=12345678
  RAZORPAY_SECRET=rGmk56w9tXdQw2NzXoNnrKCj
  RAZORPAY_KEY_ID=rzp_test_rblRlaQ16SWqAN
  NODE_ENV=
  CORS_ORIGIN=http://localhost:5173
  CLOUDINARY_API_SECRET=lTSg2io5U27-nJ3W7UlmW2npZMA
  CLOUDINARY_API_KEY=161676486991728
  CLOUDINARY_CLOUD_NAME=dneh0rgtc
  FOLDER_NAME=Edtech
  JWT_SECRET=xcfvgbhjCSHGBJmsjkghxfhbjkltyresdxfcgbhjuitrdgh
  MONGODB_URL=mongodb+srv://Siddy09:Siddhant123@cluster0.y1y0f2o.mongodb.net
  MAIL_PORT=4650
  MAIL_PASS=yfgsupxterphyejz
  MAIL_USER=efgga2800@gmail.com
  MAIL_HOST=smtp.gmail.com
  PORT=4000

